In [87]:
import numpy
import pandas as pd
from numexpr.necompiler import double
from sklearn.model_selection import train_test_split
import numpy as np


from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet, BayesianRidge, HuberRegressor, Lars
from sklearn.linear_model import LassoLars, OrthogonalMatchingPursuit, PassiveAggressiveRegressor, RANSACRegressor
from sklearn.linear_model import SGDRegressor, TheilSenRegressor, ARDRegression, TweedieRegressor, PoissonRegressor
from sklearn.linear_model import GammaRegressor, QuantileRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, BaggingRegressor
from sklearn.ensemble import ExtraTreesRegressor, HistGradientBoostingRegressor, StackingRegressor, VotingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR, LinearSVR, NuSVR
from sklearn.neighbors import KNeighborsRegressor, RadiusNeighborsRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.isotonic import IsotonicRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.dummy import DummyRegressor

In [88]:
models = [
    LinearRegression, Ridge, Lasso, ElasticNet, BayesianRidge, HuberRegressor, Lars,
    LassoLars, OrthogonalMatchingPursuit, PassiveAggressiveRegressor, RANSACRegressor,
    SGDRegressor, TheilSenRegressor, ARDRegression, TweedieRegressor, PoissonRegressor,
    GammaRegressor, QuantileRegressor,
    RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, BaggingRegressor,
    ExtraTreesRegressor, HistGradientBoostingRegressor,
    DecisionTreeRegressor,
    SVR, LinearSVR, NuSVR,
    KNeighborsRegressor, RadiusNeighborsRegressor,
    GaussianProcessRegressor,
    PLSRegression,
    DummyRegressor
]

In [89]:
df = pd.read_csv("API/Carbon Emission.csv")

In [90]:
df.head()

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
0,overweight,female,pescatarian,daily,coal,public,NaN,often,230,frequently,210,large,4,7,26,1,No,['Metal'],"['Stove', 'Oven']",2238
1,obese,female,vegetarian,less frequently,natural gas,walk/bicycle,NaN,often,114,rarely,9,extra large,3,9,38,5,No,['Metal'],"['Stove', 'Microwave']",1892
2,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595
3,overweight,male,omnivore,twice a day,wood,walk/bicycle,NaN,sometimes,157,rarely,74,medium,3,20,5,7,Sometimes,"['Paper', 'Plastic', 'Glass', 'Metal']","['Microwave', 'Grill', 'Airfryer']",1074
4,obese,female,vegetarian,daily,coal,private,diesel,often,266,very frequently,8457,large,1,3,5,6,Yes,['Paper'],['Oven'],4743

In [91]:
df['Vehicle Type'].replace(numpy.nan, 'none', inplace=True)
df = df.dropna()

C:\Users\kb148\AppData\Local\Temp\ipykernel_17524\1127611024.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Vehicle Type'].replace(numpy.nan, 'none', inplace=True)

In [92]:
df.reset_index(inplace=True)
df = df.drop(["index"], axis=1)

In [93]:
df.columns

Index(['Body Type', 'Sex', 'Diet', 'How Often Shower', 'Heating Energy Source',
       'Transport', 'Vehicle Type', 'Social Activity', 'Monthly Grocery Bill',
       'Frequency of Traveling by Air', 'Vehicle Monthly Distance Km',
       'Waste Bag Size', 'Waste Bag Weekly Count', 'How Long TV PC Daily Hour',
       'How Many New Clothes Monthly', 'How Long Internet Daily Hour',
       'Energy efficiency', 'Recycling', 'Cooking_With', 'CarbonEmission'],
      dtype='object')

In [94]:
# print(df['Transport'])
df['Monthly Grocery Bill'].unique()

array([230, 114, 138, 157, 266, 144,  56,  59, 200, 135, 146, 111, 123,
       225, 219, 104, 126, 288, 282,  69, 110, 165,  62,  94, 259,  67,
       130, 258, 189, 262, 280, 121, 174, 173, 199,  64, 100, 240, 245,
       270, 294,  87, 209, 124, 276,  90, 136, 246, 253, 281,  82,  73,
        98, 256, 287,  63, 158, 241, 176, 214, 264, 213, 125, 188, 251,
       285, 234,  91, 118,  75, 134, 202, 223, 141, 236,  95, 249,  81,
       291,  70,  89, 198,  84, 182, 275, 228, 140, 232, 115, 156, 252,
       162, 145, 205, 178, 286, 108,  76, 221, 295, 177, 193, 238, 101,
        99,  50,  71, 247, 222,  61, 137,  66, 105,  80, 210, 152, 260,
       283, 277, 203,  96, 233, 147,  83,  77, 254, 207,  93,  85, 133,
       129, 155, 171, 274, 269, 113,  72, 196,  97, 244, 106, 103, 220,
       172, 227, 161, 151, 255,  52, 139, 242, 224,  79, 271, 168, 175,
       212, 296, 217, 131, 184, 250, 297, 293, 273,  65, 231,  54,  68,
       289, 298, 170, 215, 190, 127, 185, 187,  86, 243, 292,  74, 208,
       229, 192, 284, 235, 122, 218, 117, 181, 120, 163, 278, 248, 216,
       186, 272, 191, 263, 206, 159, 204, 109, 268, 112, 107, 226, 290,
       299, 183, 211, 116,  53, 153, 279, 169,  57, 194, 179, 267, 239,
        58, 261,  92, 237, 265, 148, 128,  51, 132, 102,  55, 257, 160,
       180, 166, 195, 119, 149, 167, 142,  60, 150, 197, 143, 154, 201,
        88, 164,  78])

In [95]:
df[df.index == 2]

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,Recycling,Cooking_With,CarbonEmission
2,overweight,male,omnivore,more frequently,wood,private,petrol,never,138,never,2472,small,1,14,47,6,Sometimes,['Metal'],"['Oven', 'Microwave']",2595

In [96]:
type(df.loc[0, df.columns[1]])

str

In [97]:
mappedColumns = list(df.columns)
mappedColumns.remove("Recycling")
mappedColumns.remove("Cooking_With")

for column in mappedColumns:
    if not isinstance(df[column][0], (int, float, np.number)):
        df[column], unique = pd.factorize(df[column])
        print(f"'{column}':{unique}\n")

'Body Type':Index(['overweight', 'obese', 'underweight', 'normal'], dtype='object')

'Sex':Index(['female', 'male'], dtype='object')

'Diet':Index(['pescatarian', 'vegetarian', 'omnivore', 'vegan'], dtype='object')

'How Often Shower':Index(['daily', 'less frequently', 'more frequently', 'twice a day'], dtype='object')

'Heating Energy Source':Index(['coal', 'natural gas', 'wood', 'electricity'], dtype='object')

'Transport':Index(['public', 'walk/bicycle', 'private'], dtype='object')

'Vehicle Type':Index(['none', 'petrol', 'diesel', 'hybrid', 'lpg', 'electric'], dtype='object')

'Social Activity':Index(['often', 'never', 'sometimes'], dtype='object')

'Frequency of Traveling by Air':Index(['frequently', 'rarely', 'never', 'very frequently'], dtype='object')

'Waste Bag Size':Index(['large', 'extra large', 'small', 'medium'], dtype='object')

'Energy efficiency':Index(['No', 'Sometimes', 'Yes'], dtype='object')

In [98]:
recyclingDict = {
    "Metal" : 100,
    "Paper" : 70,
    "Plastic" : 50,
    "Glass" : 40
}

cookingWithDict = {
    "Microwave" : 10,
    "Airfryer" : 20,
    "Stove" : 30,
    "Oven" : 50,
    "Grill" : 120
}

def removeAll(myList, remove):
    newList = []
    for elementIndx in range(0, len(myList) - 1):
        if not ord(myList[elementIndx]) in remove:
            newList.append(myList[elementIndx])
    return newList

def convertLists(column, newColumn, pointMap):
    global df
    df[newColumn] = np.nan
    for index in df.index:
        recycling = list(df[column][index])
        # elements are the ascii for: [ ' ] ,
        removeelements = [91, 39, 93, 44]
        recycling = removeAll(recycling, removeelements)
        recycling = "".join(recycling)
        recycling = recycling.split(" ")
        score = 0
        if recycling[0] != "":
            for material in recycling:
                score += pointMap[material]
        df.loc[index, newColumn] = score

    df = df.drop([column], axis = 1)

convertLists("Recycling", "Recycling Score", recyclingDict)
convertLists("Cooking_With", "Cooking With Score", cookingWithDict)

In [99]:
df

,Body Type,Sex,Diet,How Often Shower,Heating Energy Source,Transport,Vehicle Type,Social Activity,Monthly Grocery Bill,Frequency of Traveling by Air,Vehicle Monthly Distance Km,Waste Bag Size,Waste Bag Weekly Count,How Long TV PC Daily Hour,How Many New Clothes Monthly,How Long Internet Daily Hour,Energy efficiency,CarbonEmission,Recycling Score,Cooking With Score
0,0,0,0,0,0,0,0,0,230,0,210,0,4,7,26,1,0,2238,100.00,80.00
1,1,0,1,1,1,1,0,0,114,1,9,1,3,9,38,5,0,1892,100.00,40.00
2,0,1,2,2,2,2,1,1,138,2,2472,2,1,14,47,6,1,2595,100.00,60.00
3,0,1,2,3,2,1,0,2,157,1,74,3,3,20,5,7,1,1074,260.00,150.00
4,1,0,1,0,0,2,2,0,266,3,8457,0,1,3,5,6,2,4743,70.00,50.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,1,2,3,0,2,3,2,230,2,268,3,5,12,27,9,2,2408,0.00,10.00
9996,3,0,3,3,0,2,4,1,234,0,5316,1,3,14,8,24,1,3084,120.00,40.00
9997,0,0,1,0,3,1,0,2,298,3,96,1,5,11,5,24,2,2377,220.00,150.00
9998,2,1,3,2,0,2,1,0,179,1,8688,3,5,19,14,5,1,4574,170.00,180.00
9999,1,1,0,3,2,2,5,2,115,2,9952,2,4,11,6,0,1,826,190.00,190.00

In [100]:
#----------------------------------------------Testing---------------------------------------------------

In [101]:
features = df.drop(["CarbonEmission"], axis=1)

In [102]:
features.columns

Index(['Body Type', 'Sex', 'Diet', 'How Often Shower', 'Heating Energy Source',
       'Transport', 'Vehicle Type', 'Social Activity', 'Monthly Grocery Bill',
       'Frequency of Traveling by Air', 'Vehicle Monthly Distance Km',
       'Waste Bag Size', 'Waste Bag Weekly Count', 'How Long TV PC Daily Hour',
       'How Many New Clothes Monthly', 'How Long Internet Daily Hour',
       'Energy efficiency', 'Recycling Score', 'Cooking With Score'],
      dtype='object')

In [103]:
classifier = df["CarbonEmission"]

In [104]:
classifier

0       2238
1       1892
2       2595
3       1074
4       4743
        ...
9995    2408
9996    3084
9997    2377
9998    4574
9999     826
Name: CarbonEmission, Length: 10000, dtype: int64

In [105]:
scoring = {}

x_train, x_test, y_train, y_test = train_test_split(features, classifier)
bot = HistGradientBoostingRegressor()
bot.fit(x_train, y_train)
bot.predict()

TypeError: HistGradientBoostingRegressor.predict() missing 1 required positional argument: 'X'

In [20]:
import joblib

joblib.dump(bot, "API/emmissions_classifier.joblib")

['emmissions_classifier.joblib']

In [21]:
scoringData = pd.Series(scoring)
scoringData.sort_values(ascending=False, inplace=True)

In [22]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [23]:
scoringData

Series([], dtype: object)

In [27]:
features.columns

Index(['Body Type', 'Sex', 'Diet', 'How Often Shower', 'Heating Energy Source',
       'Transport', 'Vehicle Type', 'Social Activity', 'Monthly Grocery Bill',
       'Frequency of Traveling by Air', 'Vehicle Monthly Distance Km',
       'Waste Bag Size', 'Waste Bag Weekly Count', 'How Long TV PC Daily Hour',
       'How Many New Clothes Monthly', 'How Long Internet Daily Hour',
       'Energy efficiency', 'Recycling Score', 'Cooking With Score'],
      dtype='object')